import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { 
  Target, 
  Sparkles, 
  Clock, 
  TrendingUp, 
  CheckCircle2,
  Brain,
  Zap,
  BarChart3,
  Calendar,
  Filter
} from "lucide-react";

export default function Landing() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50">
      {/* Header */}
      <header className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Target className="h-8 w-8 text-blue-600" />
              <span className="text-2xl font-bold bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                TaskMaster
              </span>
            </div>
            <Button onClick={() => window.location.href = "/api/login"}>
              Sign In
            </Button>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-20">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-6xl font-bold text-slate-900 mb-6">
              Boost Your Productivity with
              <span className="bg-gradient-to-r from-blue-600 to-purple-600 bg-clip-text text-transparent">
                {" "}AI-Powered Tasks
              </span>
            </h1>
            <p className="text-xl text-slate-600 mb-8 max-w-2xl mx-auto">
              Generate personalized tasks instantly, track your progress, and achieve your goals 
              with intelligent task management powered by Google Gemini AI.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button 
                size="lg" 
                className="text-lg px-8"
                onClick={() => window.location.href = "/api/login"}
              >
                <Sparkles className="h-5 w-5 mr-2" />
                Start Managing Tasks
              </Button>
              <Button 
                variant="outline" 
                size="lg" 
                className="text-lg px-8"
              >
                <Brain className="h-5 w-5 mr-2" />
                See AI in Action
              </Button>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid */}
      <section className="py-16 bg-white">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Why Choose TaskMaster?
            </h2>
            <p className="text-lg text-slate-600 max-w-2xl mx-auto">
              Your intelligent task management companion with AI-powered assistance
            </p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-blue-100 rounded-lg flex items-center justify-center mb-4">
                  <Sparkles className="h-6 w-6 text-blue-600" />
                </div>
                <CardTitle>AI Task Generation</CardTitle>
                <CardDescription>
                  Enter any topic and get 5 personalized, actionable tasks generated by Google Gemini AI
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-green-100 rounded-lg flex items-center justify-center mb-4">
                  <CheckCircle2 className="h-6 w-6 text-green-600" />
                </div>
                <CardTitle>Complete Task Management</CardTitle>
                <CardDescription>
                  Create, edit, delete, and track tasks with full CRUD operations and progress monitoring
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-purple-100 rounded-lg flex items-center justify-center mb-4">
                  <BarChart3 className="h-6 w-6 text-purple-600" />
                </div>
                <CardTitle>Progress Analytics</CardTitle>
                <CardDescription>
                  Visual progress tracking with completion rates, category breakdowns, and productivity insights
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center mb-4">
                  <Filter className="h-6 w-6 text-orange-600" />
                </div>
                <CardTitle>Smart Organization</CardTitle>
                <CardDescription>
                  Categorize tasks by type (work, learning, personal) with priority levels and time estimates
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-red-100 rounded-lg flex items-center justify-center mb-4">
                  <Brain className="h-6 w-6 text-red-600" />
                </div>
                <CardTitle>Intelligent Suggestions</CardTitle>
                <CardDescription>
                  Get AI-powered task suggestions based on your completed work and learning patterns
                </CardDescription>
              </CardHeader>
            </Card>

            <Card className="border-0 shadow-lg hover:shadow-xl transition-shadow">
              <CardHeader>
                <div className="w-12 h-12 bg-teal-100 rounded-lg flex items-center justify-center mb-4">
                  <Zap className="h-6 w-6 text-teal-600" />
                </div>
                <CardTitle>Lightning Fast</CardTitle>
                <CardDescription>
                  Modern React interface with real-time updates and seamless user experience
                </CardDescription>
              </CardHeader>
            </Card>
          </div>
        </div>
      </section>

      {/* Popular Categories */}
      <section className="py-16 bg-slate-50">
        <div className="container mx-auto px-4">
          <div className="text-center mb-12">
            <h2 className="text-3xl font-bold text-slate-900 mb-4">
              Popular Task Categories
            </h2>
            <p className="text-lg text-slate-600">
              Generate tasks for any area of your life
            </p>
          </div>
          
          <div className="flex flex-wrap justify-center gap-4">
            {[
              { name: "Learning", icon: "📚", color: "bg-blue-100 text-blue-800" },
              { name: "Work", icon: "💼", color: "bg-purple-100 text-purple-800" },
              { name: "Personal", icon: "🏠", color: "bg-pink-100 text-pink-800" },
              { name: "Health", icon: "💪", color: "bg-green-100 text-green-800" },
              { name: "Finance", icon: "💰", color: "bg-yellow-100 text-yellow-800" },
              { name: "General", icon: "⚡", color: "bg-gray-100 text-gray-800" },
            ].map((category) => (
              <Card key={category.name} className="p-4 hover:shadow-md transition-shadow cursor-pointer">
                <div className="text-center">
                  <div className="text-3xl mb-2">{category.icon}</div>
                  <h3 className="font-semibold text-slate-900">{category.name}</h3>
                  <Badge className={category.color} variant="secondary">
                    AI Generated
                  </Badge>
                </div>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-gradient-to-r from-blue-600 to-purple-600">
        <div className="container mx-auto px-4 text-center">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-4xl font-bold text-white mb-6">
              Ready to Supercharge Your Productivity?
            </h2>
            <p className="text-xl text-blue-100 mb-8">
              Join the future of task management with AI-powered assistance and intelligent insights
            </p>
            <Button 
              size="lg" 
              variant="secondary" 
              className="text-lg px-8"
              onClick={() => window.location.href = "/api/login"}
            >
              <Target className="h-5 w-5 mr-2" />
              Get Started Free
            </Button>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-slate-900 text-slate-300 py-12">
        <div className="container mx-auto px-4">
          <div className="text-center">
            <div className="flex items-center justify-center space-x-2 mb-4">
              <Target className="h-6 w-6 text-blue-400" />
              <span className="text-xl font-bold text-white">TaskMaster</span>
            </div>
            <p className="text-slate-400">
              AI-powered task management for the modern world
            </p>
          </div>
        </div>
      </footer>
    </div>
  );
}